[package]
name = "cloudyab-browser"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Headless browser engine wrapper (Obscura) with stealth features"

[dependencies]
cloudyab-types.workspace = true
cloudyab-core.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true
async-trait.workspace = true
futures.workspace = true
tokio-tungstenite.workspace = true
http.workspace = true
chrono.workspace = true
base64.workspace = true
hyper-render = { version = "0.2", default-features = false, features = ["png"] }
